version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
    volumes:
      - /home/talame/projet-tlc/db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  etherpad:
    image: etherpad/etherpad
    environment:
      AUTHENTICATION_METHOD: "apikey"
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt:ro

  mail:
    image: bytemark/smtp
    restart: always

  backend:
    build:
      context: ./api
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://db:3306/tlc
      QUARKUS_DATASOURCE_USERNAME: tlc
      QUARKUS_DATASOURCE_PASSWORD: tlc
      QUARKUS_MAILER_HOST: mail
      QUARKUS_MAILER_PORT: 25
      ETHERPAD_HOST: http://etherpad:9001
      ETHERPAD_APIKEY_PATH: /app/APIKEY.txt
    volumes:
      - ./APIKEY.txt:/app/APIKEY.txt:ro
    depends_on:
      db:
        condition: service_healthy
      mail:
        condition: service_started
      etherpad:
        condition: service_started

  frontend:
    build:
      context: ./front

  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/talame/projet-tlc/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
